# Generated by Django 4.2.5 on 2023-09-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Full',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertname_key', models.CharField()),
                ('state_key', models.CharField()),
                ('server', models.CharField()),
                ('description_key', models.FloatField()),
                ('active_at', models.DateTimeField()),
            ],
        ),
    ]
