# Generated by Django 4.2.5 on 2023-09-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full',
            name='alertname_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='full',
            name='description_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='full',
            name='server',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='full',
            name='state_key',
            field=models.CharField(max_length=255),
        ),
    ]
